FROM jenkins/jenkins:lts-jdk21

USER root

# Устанавливаем официальный стабильный пакет клиента Docker
RUN apt-get update && \
    apt-get install -y --no-install-recommends docker.io && \
    rm -rf /var/lib/apt/lists/*

USER jenkins